repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.3
  hooks:
    - id: ruff
      args: [ "--fix" ]

- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black

- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: pyright
      language: system
      types: [python]
