name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Set up uv
      run: pip install uv

    - name: Check code quality with Ruff
      run: uv run ruff check .

    - name: Check type hints with pyright
      run: uv run pyright

    - name: Run unit tests with pytest
      run: uv run pytest
